/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 76bc286b9ec7dd9182fc099e92bd9ddf)
interface __BaseEnv_Env {
	GITHUB_EVENTS_QUEUE: Queue;
	GITHUB_WEBHOOK_SECRET: string;
	ODOO_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
