/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 839b9fef9c18c9b3a48e61caf9a7ae58)
interface __BaseEnv_Env {
	GITHUB_EVENTS_QUEUE: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
